media:
  - name: graphics
    label: Graphics
    input: assets/graphics
    output: /assets/graphics
  - name: fonts
    label: Fonts
    input: assets/fonts
    output: /assets/fonts
  - name: media # Note: 'name' key is required here
    label: Media
    input: img
    output: /img

content:
  - name: changelog
    label: Changelog
    path: src/_data/changelog.json
    type: file
    list: true
    fields:
      - name: date
        label: Date
        type: string
      - name: text
        label: Update text
        type: text
        description: update information here.
      - name: link
        label: Update link
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: image
        label: Preview image
        type: image
  - name: neighbors
    label: neighbors
    path: src/_data/neighbors.json
    type: file
    list: true
    fields:
      - name: title
        label: site/button name
        type: string
      - name: URL
        label: url
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: fileextension
        label: file extension
        description: png gif or jpg idk
        type: string