media:
  - name: media # Note: 'name' key is required here
    label: Media
    input: img
    output: /img
  - name: ocIcons # Note: 'name' key is required here
    label: OC Icons
    input: img/oc/icons
    output: /img/oc/icons
  - name: ocAssets # Note: 'name' key is required here
    label: OC Assets
    input: img/oc/template
    output: /img/oc/template
  - name: art # Note: 'name' key is required here
    label: Gallery
    input: img/gallery
    output: /img/gallery
  - name: graphics
    label: Graphics
    input: assets/graphics
    output: /assets/graphics
  - name: fonts
    label: Fonts
    input: assets/fonts
    output: /assets/fonts

content:
  - name: OCJson
    label: OC Json
    type: collection
    path: src/Markdown/oc/characters
    format: json
    filename: '{fields.shortName}.11tydata.json'
    fields:
    - { name: shortName, label: First Name, type: string }
    - { name: Name, label: Name, type: string }
    - { name: Pfp, label: Bio Image, type: image}
    - name: Stats 
      label: Bio Stats
      fields:
      - { name: Pronouns, label: Pronouns, type: string }
      - { name: Age, label: Age, type: string }
      - { name: Height, label: Height, type: string }
      - { name: Setting, label: Setting, type: string }
      - { name: Species, label: Species, type: string }
      - { name: Job, label: Job, type: string }
    - name: Song
      label: Song
      fields:
        - { name: songPath, label: Song Link, type: string }
        - { name: songTitle, label: Song Title, type: string }
    - { name: Bio, label: Bio, type: rich-text }
    - { name: Story, label: Story, type: rich-text }
    - name: Refs
      label: Reference Images
      type: image
      options:
        multiple: true
        path: ocAssets
    - { name: Notes, label: Design Notes, type: string, list: true }
    - name: Traits
      label: Traits
      fields:
        - { name: Confidence, label: Confidence, type: string }
        - { name: Intelligence, label: Intelligence, type: string }
        - { name: Kindness, label: Kindness, type: string }
        - { name: Social, label: Social, type: string }
        - { name: Luck, label: Luck, type: string }
    - name: Ships
      label: Relations
      list: true
      fields:
        - { name: pfp, label: icon, type: image }
        - { name: name, label: Name, type: string}
        - { name: relation, label: Relationship, type: string }
        - { name: description, label: Description, type: string }
        
  - name: illustration
    label: Illustration
    type: collection
    path: src/Markdown/art/illustration
    fields:
    - { name: layout, hidden: true, type: string, default: art/illustration/posts.njk }
    - { name: title, label: Title, type: string }
    - { name: date, label: Date, type: date }
    - { name: image, label: Image, media: art, type: image }
    - { name: thumb, label: Thumbnail Image, media: art, type: image }
    - name: tags
      label: Tags
      type: select
      options:
        multiple: true
        creatable: true
        values: [ Illustration ]
  - name: design
    label: Design
    type: collection
    path: src/Markdown/art/design
    fields:
    - { name: layout, hidden: true, type: string, default: art/illustration/posts.njk }
    - { name: title, label: Title, type: string }
    - { name: date, label: Date, type: date }
    - { name: description, label: Description, type: string }
    - { name: image, label: Image, media: art, type: image }
    - name: tags
      label: Tags
      type: select
      options:
        multiple: true
        creatable: true
        values: [ Design ]
  - name: medialog
    label: Medialog
    type: collection
    path: src/Markdown/medialog/posts
    fields:
    - { name: layout, hidden: true, type: string, default: medialog_index.njk }
    - { name: permalink, hidden: true, type: string, default: "{{ page.filePathStem }}.html" }
    - { name: tags, hidden: true, type: string, default: medialog }
    - { name: title, label: Title, type:  string }
    - { name: date, label: Date, type: date }
    - { name: cover, label: Cover, type: image }
    - { name: body, label: Body, type: rich-text }
    - name: type
      label: Type
      type: select
      options:
        values: [ movie, book, game, misc ]
    - name: ratings
      label: Ratings
      type: select
      options:
        multiple: true
        values:
        - value: bored
          label: Bored
        - value: brainrot
          label: I feel crazy
        - value: dislike
          label: Disliked
        - value: frustrating
          label: Frustrating
        - value: fun
          label: Fun
        - value: hate
          label: Hate
        - value: imagine
          label: Imagining
        - value: like
          label: Liked
        - value: love
          label: Loved
        - value: scared
          label: SCARY
        - value: think
          label: Thought Provoking
        - value: weep
          label: Emotional
        - value: wow
          label: Wowed Me
        - value: wtf
          label: wtf
        - value: yahoo
          label: YAAAY
  - name: changelog
    label: Changelog
    path: src/_data/changelog.json
    type: file
    list: true
    fields:
      - name: date
        label: Date
        type: string
      - name: text
        label: Update text
        type: text
        description: update information here.
      - name: link
        label: Update link
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: image
        label: Preview image
        type: image
  - name: neighbors
    label: Neighbors
    path: src/_data/neighbors.json
    type: file
    list: true
    fields:
      - name: title
        label: site/button name
        type: string
      - name: URL
        label: url
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: fileExtension
        label: fileExtension
        description: png gif or jpg idk
        type: string